all:
  hosts:
    node1:
      ansible_host: 10.0.26.10
      ip: 10.0.26.10
      access_ip: 10.0.26.10
      disk_volume_device_1: /dev/sdb1
      disk_volume_unmount: /disk2
    node2:
      ansible_host: 10.0.26.11
      ip: 10.0.26.11
      access_ip: 10.0.26.11
      disk_volume_device_1: /dev/sdb1
      disk_volume_unmount: /disk2
    node3:
      ansible_host: 10.0.26.13
      ip: 10.0.26.13
      access_ip: 10.0.26.13
      disk_volume_device_1: /dev/sdb1
      disk_volume_unmount: /disk2
    node4:
      ansible_host: 10.0.26.14
      ip: 10.0.26.14
      access_ip: 10.0.26.14
    node5:
      ansible_host: 10.0.26.15
      ip: 10.0.26.15
      access_ip: 10.0.26.15
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    gfs-cluster:
      hosts:
        node1:
        node2:
        node3:        
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    network-storage:
      children:
        gfs-cluster:
    calico-rr:
      hosts: {}
